#!/usr/bin/env python3
"""How much of a line may text fill before Word breaks it?  The δ sweep.

The sibling measured PowerPoint's budget as exact -- ``sum of advances <= width - insets``,
inclusive, no slack -- with a box of ``k * size + δ`` and one repeated character, sweeping
δ through zero.  For Word that is a hypothesis (ROADMAP.md, Phase 3), and this probe
tests it the same way, in Word's own unit: Phase 2 measured that x is held in 1/4096 pt,
that an advance is the unrounded ``advance / upm x size`` (for a 2048-upm face at a
half-point size, exactly ``advance x half points`` units) and that a twip length lands on
that grid, so a column of ``5m`` twips is exactly ``1024m`` units.  Everything here is
authored in multiples of 5 twips (a page 11900 wide, margins 1440, indents), so the
budget and the text's width are both exact integers and δ, their difference, is known to
the unit (1/4096 pt, 0.001 device px).

Every case is one paragraph whose line under test is **``W1 W2``**: a fixed first word,
a space, and a second word composed of ``H n e s`` so that the line's width is the
budget less δ.  Under the hypothesis the line holds ``W2`` exactly when δ >= 0.  δ is
swept over +-1024, +-205, +-41, +-9, +-3, +-1 and 0 units (even values at even sizes,
where only even differences exist).  Families:

* ``mid`` -- ``W1 W2 Hnnn``: the ordinary break at a space;
* ``last`` -- ``W1 W2`` and nothing more: the paragraph mark follows the line;
* ``trail`` -- ``W1 W2``, six spaces, ``Hnnn``: do spaces at the line's end count?
* ``second`` -- a first line of one word, then ``W1 W2 Hnnn``: the budget of a
  paragraph's later line;
* ``first`` -- ``w:ind/@w:firstLine``: the first line's budget is the column less it;
* ``hang`` -- ``w:ind/@w:left`` = ``@w:hanging``: the first line starts at the margin
  and has the whole column;
* ``single`` -- ``W2 Hnnn`` with ``W2`` alone as wide as the budget less δ: a word too
  long for an empty line, which Word must split somewhere.

Columns run from about 1500 to 9020 twips (``w:ind`` left and right, multiples of 5);
eight faces (Calibri, Arial, Times New Roman, Cambria, Georgia, Verdana, Courier New,
Aptos) at 9.5, 11 and 14.5 pt.  Then the same ``mid``/``last``/``trail`` cases for
four faces in three more documents, with ``settings.xml`` at compatibility modes 12, 14
and 15, since the real documents are written in all three.

The advances below are the faces' ``hmtx`` values -- measurements of the fonts Word lays
out with, frozen here so that the probe is regenerated byte for byte without a font file;
``read_wrap_budget_probe.py`` checks them against the installed faces.
"""

from __future__ import annotations

import functools
from dataclasses import dataclass

import probe_docx as w
import wml

PAGE_WIDTH = 11900
PAGE_HEIGHT = 16840
MARGIN = 1440
COLUMN = PAGE_WIDTH - 2 * MARGIN  # 9020 twips

#: ``hmtx`` advances (units per em 2048) of the characters the probe composes words from.
WIDTHS = {
    "Calibri": {"H": 1276, "n": 1076, "e": 1019, "s": 801, "o": 1080, "i": 470, "a": 981, "t": 686, "r": 714, "d": 1076, "l": 470, "m": 1636, "u": 1076, " ": 463},
    "Arial": {"H": 1479, "n": 1139, "e": 1139, "s": 1024, "o": 1139, "i": 455, "a": 1139, "t": 569, "r": 682, "d": 1139, "l": 455, "m": 1706, "u": 1139, " ": 569},
    "Times New Roman": {"H": 1479, "n": 1024, "e": 909, "s": 797, "o": 1024, "i": 569, "a": 909, "t": 569, "r": 682, "d": 1024, "l": 569, "m": 1593, "u": 1024, " ": 512},
    "Cambria": {"H": 1406, "n": 1143, "e": 999, "s": 880, "o": 1087, "i": 569, "a": 1000, "t": 693, "r": 847, "d": 1136, "l": 556, "m": 1704, "u": 1131, " ": 451},
    "Georgia": {"H": 1669, "n": 1210, "e": 990, "s": 885, "o": 1104, "i": 600, "a": 1032, "t": 707, "r": 839, "d": 1176, "l": 586, "m": 1804, "u": 1178, " ": 494},
    "Verdana": {"H": 1539, "n": 1296, "e": 1220, "s": 1067, "o": 1243, "i": 562, "a": 1230, "t": 807, "r": 874, "d": 1276, "l": 562, "m": 1992, "u": 1296, " ": 720},
    "Courier New": {"H": 1229, "n": 1229, "e": 1229, "s": 1229, "o": 1229, "i": 1229, "a": 1229, "t": 1229, "r": 1229, "d": 1229, "l": 1229, "m": 1229, "u": 1229, " ": 1229},
    "Aptos": {"H": 1448, "n": 1129, "e": 1079, "s": 995, "o": 1130, "i": 489, "a": 1088, "t": 662, "r": 685, "d": 1148, "l": 533, "m": 1747, "u": 1144, " ": 416},
}
#: The letters the second word is composed of.  Their advances reach every width in any
#: face but Courier New, whose are all 1229: its δ is the nearest reachable one, and is
#: recorded as it is rather than as targeted.
POOL = "Hnesoiatrdlmu"
FACES = tuple(WIDTHS)
SIZES = (19, 22, 29)
DELTAS = (-1024, -205, -41, -9, -3, -1, 0, 1, 3, 9, 41, 205, 1024)
FAMILIES = ("mid", "last", "trail", "second", "first", "hang", "single")
#: Column widths the cases cycle through, in twips (the case's own is the nearest that
#: makes δ exact).
COLUMNS = (1500, 2600, 4000, 6000, 8800)
W1 = "Hnio"
TAIL = "Hnnn"
MODES = {"none": None, "12": 12, "14": 14, "15": 15}
MODE_FACES = ("Calibri", "Times New Roman", "Georgia", "Courier New")
MODE_SIZES = (22, 29)
MODE_FAMILIES = ("mid", "last", "trail")


@dataclass(frozen=True)
class Case:
    setting: str
    family: str
    face: str
    half_points: int
    delta: int  # budget less the width of the line under test, in 1/4096 pt
    ind_left: int
    ind_right: int
    first_line: int
    hanging: int
    lead: str  # a first line of one word (family ``second``), else ""
    under_test: str  # the line under test's text, spaces included
    rest: str  # what follows it in the paragraph

    @property
    def text(self) -> str:
        return " ".join(part for part in (self.lead, self.under_test) if part) + self.rest

    @property
    def fits(self) -> bool:
        """The hypothesis: the line holds all of ``under_test`` iff δ >= 0."""
        return self.delta >= 0


def _units(face: str, text: str, half_points: int) -> int:
    return sum(WIDTHS[face][c] for c in text) * half_points


def _sums(face: str) -> list:
    """For every width up to the widest column at the largest size, the word of
    :data:`POOL` letters with the fewest characters that is exactly that wide (in font
    units), or ``None`` -- a coin-change table."""
    limit = COLUMN * 1024 // 5 // min(SIZES + MODE_SIZES) + 1
    widths = sorted({WIDTHS[face][c]: c for c in POOL}.items())
    best: list = [None] * (limit + 1)
    best[0] = ""
    for total in range(1, limit + 1):
        for width, char in widths:
            if width <= total and best[total - width] is not None and (
                    best[total] is None or len(best[total - width]) + 1 < len(best[total])):
                best[total] = best[total - width] + char
    return [None if word is None else "".join(sorted(word, key=POOL.index)) for word in best]


_SUMS: dict[str, list] = {}


def _layout(family: str, col: int) -> tuple[int, int, int, int] | None:
    """``(ind_left, ind_right, first_line, hanging)`` giving the line under test ``col``
    twips: it starts ``ind_left - hanging + first_line`` into the column and ends
    ``ind_right`` short of its right edge."""
    first_line = hanging = ind_left = 0
    if family == "first":
        first_line = 720
    elif family == "hang":
        ind_left = hanging = 720
    ind_right = COLUMN - col - (ind_left - hanging + first_line)
    if ind_right < 0 or col < 1000:
        return None
    return ind_left, ind_right, first_line, hanging


def _case(setting: str, family: str, face: str, hp: int, delta: int, target_col: int) -> Case | None:
    """The case nearest ``target_col`` twips of column whose δ is exactly ``delta`` -- or,
    where no column is (Courier New), the one whose δ is nearest it on the same side of
    zero."""
    fixed = 0 if family == "single" else _units(face, W1 + " ", hp)
    if face not in _SUMS:
        _SUMS[face] = _sums(face)
    sums = _SUMS[face]
    best = None
    for step in range(0, 1600):
        for col in {target_col + 5 * step, target_col - 5 * step}:
            layout = _layout(family, col)
            if layout is None:
                continue
            budget = col * 1024 // 5
            lead = ""
            if family == "second":
                # One word that fits the line with room to spare, but not with W1 after it.
                n = (budget - _units(face, W1, hp) // 2) // (WIDTHS[face]["n"] * hp)
                lead = "H" + "n" * (n - 1)
                if _units(face, lead, hp) > budget or _units(face, lead + " " + W1, hp) <= budget:
                    continue
            want = budget - delta - fixed
            if want > 0 and want % hp == 0 and want // hp < len(sums) and sums[want // hp]:
                best = (0, col, layout, lead, sums[want // hp])
            elif face == "Courier New":
                unit = WIDTHS[face]["H"] * hp
                k = want // unit if delta >= 0 else -(-want // unit)
                actual = budget - fixed - k * unit
                if k > 0 and (actual >= 0) == (delta >= 0) and (
                        best is None or abs(actual - delta) < best[0]):
                    best = (abs(actual - delta), col, layout, lead, "H" * k)
            if best is not None and best[0] == 0:
                break
        if best is not None and best[0] == 0:
            break
    if best is None:
        return None
    _, col, (ind_left, ind_right, first_line, hanging), lead, word = best
    actual = col * 1024 // 5 - fixed - _units(face, word, hp)
    if family == "single":
        return Case(setting, family, face, hp, actual, ind_left, ind_right, first_line, hanging,
                    "", word, " " + TAIL)
    rest = {"last": "", "trail": " " * 6 + TAIL}.get(family, " " + TAIL)
    return Case(setting, family, face, hp, actual, ind_left, ind_right, first_line, hanging,
                lead, f"{W1} {word}", rest)


@functools.lru_cache(maxsize=None)
def cases() -> tuple[Case, ...]:
    out = []
    index = 0
    for setting in MODES:
        faces, sizes, families = (FACES, SIZES, FAMILIES) if setting == "none" else (
            MODE_FACES, MODE_SIZES, MODE_FAMILIES)
        for family in families:
            for face in faces:
                for hp in sizes:
                    for delta in DELTAS:
                        if hp % 2 == 0 and delta % 2:
                            delta += 1 if delta > 0 else -1
                        case = _case(setting, family, face, hp, delta, COLUMNS[index % len(COLUMNS)])
                        index += 1
                        if case is None:
                            raise RuntimeError(f"no case for {setting} {family} {face} {hp} {delta}")
                        out.append(case)
    return tuple(out)


def _paragraph(case: Case) -> str:
    run = w.run(case.text, case.face, case.half_points)
    ind = {"left": case.ind_left, "right": case.ind_right}
    if case.first_line:
        ind["firstLine"] = case.first_line
    if case.hanging:
        ind["hanging"] = case.hanging
    fonts = {"ascii": case.face, "hAnsi": case.face, "eastAsia": case.face, "cs": case.face}
    mark = {"rFonts": fonts, "sz": case.half_points, "szCs": case.half_points}
    return wml.paragraph(run, mark=mark, spacing={"before": 0, "after": 0, "line": 240, "lineRule": "auto"},
                         ind=ind)


def section() -> str:
    return (
        "<w:sectPr>"
        f'<w:pgSz w:w="{PAGE_WIDTH}" w:h="{PAGE_HEIGHT}"/>'
        f'<w:pgMar w:top="{MARGIN}" w:right="{MARGIN}" w:bottom="{MARGIN}" w:left="{MARGIN}"'
        ' w:header="720" w:footer="720" w:gutter="0"/>'
        "</w:sectPr>"
    )


def documents() -> dict[str, list[Case]]:
    out: dict[str, list[Case]] = {}
    for case in cases():
        out.setdefault(f"wrap-budget-{case.setting}", []).append(case)
    return out


def build(name: str) -> bytes:
    group = documents()[name]
    setting = group[0].setting
    extra = ()
    if MODES[setting] is not None:
        extra = (wml.settings_part({"val": "en-GB"}, compatibility_mode=MODES[setting]),)
    body = "".join(_paragraph(case) for case in group)
    return w.package(body, final_section=section(), extra_parts=extra)


if __name__ == "__main__":
    for name, group in documents().items():
        print(name, len(group), "paragraphs", len(build(name)), "bytes")
