#!/usr/bin/env python3
"""Word's PDF export of a ``.docx``, cached by content, with the recovery in one place.

Phase 0.8 owed two small things and both are here because Phase 2 exports many probes:

* **A cache keyed by the input's SHA-256.**  An export costs several seconds of a
  foreground application stealing focus.  A probe regenerated byte-for-byte identical
  must not re-export, and a probe that changed by one byte must.  The key is the hash of
  the ``.docx`` bytes -- not its name, which is how a stale PDF gets measured.
* **The recovery helper.**  ``pkill -x "Microsoft Word"`` plus deleting the ``~$`` lock
  a failed attempt leaves behind (see the AppleScript header for why that lock wedges
  the next open).  It was inline in two places; it now lives here.

**Word is one instance per machine, shared with docx-agent.**  Every launch, export,
re-save and recovery happens while holding an advisory ``flock`` on :data:`WORD_LOCK`,
the file docx-agent's oracle locks (:func:`word`).  The lock is waited for, up to
:data:`LOCK_TIMEOUT`; a Word found running once it is held is someone else's and is never
quit -- :class:`WordBusy` instead; only the Word this process started is quit, and only
the ``~$`` files in :data:`ORACLE_DIR` are deleted.  A cached export takes no lock.

Everything lands in the Office group container (``ORACLE_DIR`` below) because Word is
sandboxed and every Office app may read and write there without a per-folder grant --
see the fourth note in ``word_export_pdf.applescript``.  The staged ``.docx`` is deleted after a successful
export so the directory holds only ``<sha>.pdf`` files plus whatever Phase 0 left there.

Usage::

    python tools/oracle.py probe.docx      # prints the PDF path
"""

from __future__ import annotations

import contextlib
import hashlib
import io
import os
import re
import subprocess
import sys
import time
import zipfile
from pathlib import Path
from typing import Iterator

try:
    import fcntl
except ImportError:  # Windows: there is no Word oracle there (it drives Word on macOS)
    fcntl = None

REPO = Path(__file__).resolve().parent.parent
#: The Office group container: Word is sandboxed, and every Office app may read and write
#: here without a per-folder grant.
GROUP_CONTAINER = Path.home() / "Library" / "Group Containers" / "UBF8T346G9.Office"
#: The one place the oracle's location is written.  The path contains a space; every
#: caller passes it as a single argv element, never through a shell.
ORACLE_DIR = GROUP_CONTAINER / "docx2svg-oracle"
#: The machine-wide Word lock, shared with docx-agent's oracle (its ``tests/oracle.py``):
#: an advisory ``flock`` on this file is held around every launch, export, re-save and
#: recovery, so neither project's recovery can quit Word under the other's export.
WORD_LOCK = GROUP_CONTAINER / "word-oracle.lock"
#: How long to wait for the lock, seconds (``DOCX2SVG_WORD_LOCK_TIMEOUT``): another job's
#: batch of exports is waited out; past this, :class:`WordBusy`.
LOCK_TIMEOUT = float(os.environ.get("DOCX2SVG_WORD_LOCK_TIMEOUT", "600"))
SCRIPT = REPO / "tools" / "word_export_pdf.applescript"


class WordBusy(RuntimeError):
    """The Word lock stayed held past the timeout, or Word is running and this process
    did not start it: the oracle does not run (a test skips)."""


def word_running() -> bool:
    return subprocess.run(["pgrep", "-x", "Microsoft Word"], capture_output=True).returncode == 0


#: How deep this process is in :func:`word`: the lock is taken once, by the outermost.
_depth = 0


@contextlib.contextmanager
def word(timeout: float | None = None, *, refuse_running: bool = True) -> Iterator[None]:
    """Hold the machine-wide Word lock (:data:`WORD_LOCK`) for a run of Word work.

    **Blocking, with a timeout**: the lock is waited for, polling once a second, up to
    ``timeout`` (:data:`LOCK_TIMEOUT`), then :class:`WordBusy` -- a probe batch waits out
    docx-agent's oracle rather than fail, and never runs beside it.  Re-entrant within the
    process.  Once it is held, a Word still running (after ten seconds' grace for one
    quitting) was not started by this process -- whoever holds the lock quits the Word it
    started before releasing it -- so it is someone's, and is **never quit**:
    :class:`WordBusy` instead (``refuse_running``).  On release, a Word this process started
    and left running is quit (:func:`recover`)."""
    global _depth
    if _depth:
        _depth += 1
        try:
            yield
        finally:
            _depth -= 1
        return
    if fcntl is None:
        raise WordBusy("the Word oracle runs on macOS only")
    GROUP_CONTAINER.mkdir(parents=True, exist_ok=True)
    handle = open(WORD_LOCK, "a+")
    try:
        deadline = time.monotonic() + (LOCK_TIMEOUT if timeout is None else timeout)
        while True:
            try:
                fcntl.flock(handle, fcntl.LOCK_EX | fcntl.LOCK_NB)
                break
            except BlockingIOError:
                if time.monotonic() >= deadline:
                    raise WordBusy(f"another job has held the Word lock ({WORD_LOCK}) for longer than the "
                                   f"timeout") from None
                time.sleep(1)
        try:
            for _ in range(100):
                if not word_running():
                    break
                time.sleep(0.1)
            if refuse_running and word_running():
                raise WordBusy("Microsoft Word is running and this process did not start it: it is in use, "
                               "and is left alone")
            _depth = 1
            try:
                yield
            finally:
                _depth = 0
                if refuse_running:
                    _recover()
        finally:
            fcntl.flock(handle, fcntl.LOCK_UN)
    finally:
        handle.close()


def recover(stem: str | None = None) -> None:
    """Quit the Word this process started and remove every ``~$`` lock in the oracle
    directory.

    Under the Word lock (:func:`word`) any Word running is the one this process started --
    the lock was taken with Word not running -- and is quit.  Called without it, as a probe
    script's ``finally`` does after its exports (each of which quit its Word before
    releasing the lock), it takes the lock, **leaves Word alone** (a Word running then is
    someone else's) and removes only the ``~$`` locks in :data:`ORACLE_DIR`, which only
    this project writes.

    ``stem`` is accepted for symmetry with callers that know which document failed, but
    every lock is removed: a lock from *any* earlier failure is enough to wedge the next
    export, and none of them is ever wanted.
    """
    if _depth:
        _recover()
        return
    with word(refuse_running=False):
        _clear_locks()


def _recover() -> None:
    """Under the lock: quit Word (this process's) and clear the ``~$`` locks."""
    if word_running():
        subprocess.run(["pkill", "-x", "Microsoft Word"], check=False)
    # Wait for Word to be gone.  Launching the next export while the previous Word is
    # still quitting makes ``activate`` fail with exit status 1 and nothing on stdout --
    # measured: the first export through this helper failed exactly that way, and the
    # same command run by hand a moment later succeeded.
    for _ in range(100):
        if not word_running():
            break
        time.sleep(0.1)
    _clear_locks()


def _clear_locks() -> None:
    for lock in ORACLE_DIR.glob("~$*"):
        lock.unlink(missing_ok=True)


def run(script: Path, data: bytes, staged: Path, out: Path, *, extra: list[str] = (), timeout: int = 600,
        what: str = "export") -> Path:
    """Run a Word AppleScript as ``osascript script staged out *extra`` under the Word lock,
    ``data`` staged at ``staged`` (in :data:`ORACLE_DIR`): recovered before each of two
    attempts and after, the staged copy deleted.  Returns ``out``; ``RuntimeError`` when
    Word fails twice or reports success and writes nothing."""
    with word():
        ORACLE_DIR.mkdir(exist_ok=True)
        for attempt in (1, 2):
            recover()
            staged.write_bytes(data)
            try:
                subprocess.run(["osascript", str(script), str(staged), str(out), *extra], check=True, timeout=timeout,
                               capture_output=True)
            except (subprocess.CalledProcessError, subprocess.TimeoutExpired) as error:
                if attempt == 2:
                    recover()
                    staged.unlink(missing_ok=True)
                    detail = getattr(error, "stderr", b"") or b""
                    raise RuntimeError(
                        f"Word failed to {what} {staged.name}: {error} {detail.decode(errors='replace')}"
                    ) from error
                continue
            # Word returns success and writes nothing in several failure modes; the exit
            # status is not the check.
            if out.exists():
                break
        staged.unlink(missing_ok=True)
        recover()
    if not out.exists():
        raise RuntimeError(f"Word exited 0 and wrote nothing for {staged.name} ({what})")
    return out


#: What the export shows of a document's tracked changes and comments
#: (``word_export_pdf.applescript``, "Revisions"): ``final`` the *No Markup* view -- what
#: the renderer draws, and the default -- or ``accept``, every revision accepted first.
VIEWS = ("final", "accept")

#: Markup Word draws in its default view: a revision of any kind, or a comment.
_MARKUP = re.compile(rb"<w:(?:ins|del|moveFrom|moveTo|cellIns|cellDel|cellMerge|numberingChange|"
                     rb"(?:rPr|pPr|sectPr|tblPr|trPr|tcPr|tblGrid|tblPrEx)Change|commentReference|"
                     rb"commentRangeStart)[\s/>]")


def has_markup(data: bytes) -> bool:
    """Whether any XML part of the package holds a revision or a comment."""
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        return any(_MARKUP.search(archive.read(name)) for name in archive.namelist()
                   if name.startswith("word/") and name.endswith(".xml"))


def export(docx: Path | bytes, *, name: str = "probe", view: str = "final") -> Path:
    """Return Word's PDF of ``docx``, exporting only if this exact content is new.

    ``view`` (:data:`VIEWS`) is part of the cache key.  A document with no markup
    (:func:`has_markup`) exports identically in every view (measured), so its export is
    the one it always was, under the name it always had; one with markup is exported in
    the view asked for and named for it -- never in Word's default *All Markup*, which
    draws balloons in a pane and moves the text aside."""
    if view not in VIEWS:
        raise ValueError(f"no export view {view!r}")
    data = docx.read_bytes() if isinstance(docx, Path) else docx
    digest = hashlib.sha256(data).hexdigest()[:16]
    if not has_markup(data):
        view = None
    suffix = f"-{view}" if view else ""
    pdf = ORACLE_DIR / f"{name}-{digest}{suffix}.pdf"
    if pdf.exists():
        return pdf

    staged = ORACLE_DIR / f"{name}-{digest}.docx"
    return run(SCRIPT, data, staged, pdf, extra=[view] if view else [])


RESAVE_SCRIPT = REPO / "tools" / "word_save_docx.applescript"


def resave(docx: bytes, *, name: str = "probe") -> bytes:
    """``docx`` as Word saves it again (``word_save_docx.applescript``): what Word
    computes and caches on saving -- a SmartArt diagram's laid-out drawing -- written into
    the file.  Cached by content, as :func:`export` is."""
    digest = hashlib.sha256(docx).hexdigest()[:16]
    saved = ORACLE_DIR / f"{name}-{digest}-saved.docx"
    if saved.exists():
        return saved.read_bytes()
    staged = ORACLE_DIR / f"{name}-{digest}.docx"
    return run(RESAVE_SCRIPT, docx, staged, saved, what="save").read_bytes()


if __name__ == "__main__":
    print(export(Path(sys.argv[1]), name=Path(sys.argv[1]).stem))
