#!/usr/bin/env python3
"""Write ``src/docx2svg/recorded.py``: the integers Word lays the symbol faces out with.

A symbol-font bullet (Symbol's U+F0B7, Wingdings' U+F0A7, U+F0D8, U+F076...) is the
commonest list label after a plain one, and the faces it is set in are Microsoft's, with
no open clone: where they are absent the layout could not measure the label and stopped
at the first bulleted paragraph.  What the layout needs of them is a handful of integers
-- the vertical metrics, the script sizes, the underline and strikeout geometry and an
advance per character -- and those are facts about the face, which this project records
(the files never enter the repository).

The integers are read with :class:`docx2svg.fonts.InstalledFonts` -- the copies Word lays
out with (Word's bundle's SymbolMT, which ``PREFER_BUNDLE`` picks over macOS's Symbol;
macOS's Wingdings) -- so the recorded face answers exactly as the installed one would.
``tests/test_fonts.py`` holds the module to the installed faces where they are present.

Usage::

    python tools/record_symbol_faces.py     # rewrites src/docx2svg/recorded.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from docx2svg.fonts import InstalledFonts  # noqa: E402

#: The faces recorded, as Word names them.
FACES = ("Symbol", "Wingdings")
#: Their characters: the private-use block a symbol font's ``(3, 0)`` cmap maps (Word
#: writes a bullet's character there) and, for Symbol, the same codes below U+0100.
RANGES = (range(0xF020, 0xF100), range(0x20, 0x100))

HEADER = '''"""The integers Word lays two symbol faces out with, recorded for hosts that lack them.

Generated by ``tools/record_symbol_faces.py`` from the copies Word lays out with (Word's
bundle's SymbolMT; macOS's Wingdings) -- do not edit.  Facts about the faces, not the
faces: no outline, no file.  :class:`docx2svg.fonts.InstalledFonts` falls back to these
only where neither the face nor an embedded copy of it is found, and reports it
(``font-substituted``); what is drawn then is the character's Unicode equivalent
(:data:`UNICODE`) in a generic face, at the position Word's face gives it.
"""

'''


def main() -> int:
    fonts = InstalledFonts()
    lines = [HEADER, "#: family (lowercased) -> (unitsPerEm, ascent, descent, lineGap, superscript size,",
             "#: subscript size, superscript offset, subscript offset), as docx2svg.vertical.FaceMetrics.",
             "METRICS = {"]
    decorations, advances = {}, {}
    for family in FACES:
        face = fonts.face(family)
        if face is None or fonts.substitutions:
            print(f"{family} is not installed here: nothing recorded", file=sys.stderr)
            return 1
        m = face.metrics
        lines.append(f"    {family.lower()!r}: ({m.units_per_em}, {m.ascent}, {m.descent}, {m.line_gap}, "
                     f"{m.superscript_size}, {m.subscript_size}, {m.superscript_offset}, {m.subscript_offset}),")
        decorations[family.lower()] = face.decorations.integers()
        advances[family.lower()] = {code: face.advance(chr(code)) for r in RANGES for code in r
                                    if face.advance(chr(code)) is not None}
    lines.append("}")
    lines.append("")
    lines.append("#: family -> docx2svg.fonts.Decorations' integers, in its order.")
    lines.append("DECORATIONS = {")
    for family, values in decorations.items():
        lines.append(f"    {family!r}: {tuple(values)!r},")
    lines.append("}")
    lines.append("")
    lines.append("#: family -> {code point: advance, in font units}.")
    lines.append("ADVANCES = {")
    for family, table in advances.items():
        lines.append(f"    {family!r}: {{")
        items = [f"0x{code:04X}: {width}" for code, width in sorted(table.items())]
        for k in range(0, len(items), 6):
            lines.append("        " + ", ".join(items[k:k + 6]) + ",")
        lines.append("    },")
    lines.append("}")
    lines.append(UNICODE)
    (REPO / "src" / "docx2svg" / "recorded.py").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


#: Written as is: the glyphs' Unicode equivalents, the bullets Word's bullet library offers
#: and their near kin, each named in the Unicode character database.  A character not here
#: is drawn as itself (in the private-use block, which a generic face does not draw).
UNICODE = '''
#: family -> {code point: what is drawn in its place}: Word's bullet glyphs, by their names
#: in the Unicode character database.
UNICODE = {
    "symbol": {
        0xF0B7: "\\u2022", 0x00B7: "\\u2022",  # BULLET
        0xF0A8: "\\u2666", 0x00A8: "\\u2666",  # BLACK DIAMOND SUIT
        0xF0D8: "\\u00ac", 0x00D8: "\\u00ac",  # NOT SIGN
        0xF0DE: "\\u21d2", 0x00DE: "\\u21d2",  # RIGHTWARDS DOUBLE ARROW
        0xF0AE: "\\u2192", 0x00AE: "\\u2192",  # RIGHTWARDS ARROW
        0xF02D: "\\u2212", 0x002D: "\\u2212",  # MINUS SIGN
    },
    "wingdings": {
        0xF06C: "\\u25cf",  # BLACK CIRCLE
        0xF06E: "\\u25a0",  # BLACK SQUARE
        0xF06F: "\\u25a1",  # WHITE SQUARE
        0xF071: "\\u2751",  # LOWER RIGHT SHADOWED WHITE SQUARE
        0xF075: "\\u25c6",  # BLACK DIAMOND
        0xF076: "\\u2756",  # BLACK DIAMOND MINUS WHITE X
        0xF0A7: "\\u25aa",  # BLACK SMALL SQUARE
        0xF0D8: "\\u27a2",  # THREE-D TOP-LIGHTED RIGHTWARDS ARROWHEAD
        0xF0E8: "\\u2794",  # HEAVY WIDE-HEADED RIGHTWARDS ARROW
        0xF0FC: "\\u2713",  # CHECK MARK
        0xF0FE: "\\u2611",  # BALLOT BOX WITH CHECK
    },
}'''


if __name__ == "__main__":
    raise SystemExit(main())
