#!/usr/bin/env python3
"""Write ooxml-common's ``recorded_symbol_faces.py``: the integers Word lays the symbol
faces out with.

A symbol-font bullet (Symbol's U+F0B7, Wingdings' U+F0A7, U+F0D8, U+F076...) is the
commonest list label after a plain one, and the faces it is set in are Microsoft's, with
no open clone: where they are absent the layout could not measure the label and stopped
at the first bulleted paragraph.  What the layout needs of them is a handful of integers
-- the vertical metrics, the script sizes, the underline and strikeout geometry and an
advance per character -- and those are facts about the face, which this project records
(the files never enter the repository).

The integers are read with :class:`docx2svg.fonts.InstalledFonts` -- the copies Word lays
out with (Word's bundle's SymbolMT, which ``PREFER_BUNDLE`` picks over macOS's Symbol;
macOS's Wingdings) -- so the recorded face answers exactly as the installed one would.
``tests/test_fonts.py`` holds the module to the installed faces where they are present.

The module lives in ooxml-common, so pptx2svg lays an absent Symbol or Wingdings out at
the same advances; this script writes it into a sibling checkout (``--out`` to say
where).  What the symbols are drawn as is ooxml-common's
:mod:`ooxml_common.text.symbol_fonts`, from the Unicode Consortium's tables.

Usage::

    python tools/record_symbol_faces.py     # rewrites ../ooxml-common/src/ooxml_common/text/recorded_symbol_faces.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "src"))

from docx2svg.fonts import InstalledFonts  # noqa: E402

#: The faces recorded, as Word names them.
FACES = ("Symbol", "Wingdings")
#: Their characters: the private-use block a symbol font's ``(3, 0)`` cmap maps (Word
#: writes a bullet's character there) and, for Symbol, the same codes below U+0100.
RANGES = (range(0xF020, 0xF100), range(0x20, 0x100))

HEADER = '''"""The integers Word lays two symbol faces out with, recorded for hosts that lack them.

Generated by docx2svg's ``tools/record_symbol_faces.py`` from the copies Word lays out with
(Word's bundle's SymbolMT; macOS's Wingdings) -- do not edit.  Facts about the faces, not
the faces: no outline, no file.  Shared here so both renderers lay an absent Symbol or
Wingdings out at the face's own advances: docx2svg's ``RecordedFace``, and pptx2svg's
measurer through :func:`ooxml_common.text.symbol_fonts.recorded_font_metrics`.  What is
drawn in the face's place is :mod:`ooxml_common.text.symbol_fonts`' business.
"""

'''

#: Where the module is written: ooxml-common, in a checkout beside this one.
TARGET = REPO.parent / "ooxml-common" / "src" / "ooxml_common" / "text" / "recorded_symbol_faces.py"


def main() -> int:
    fonts = InstalledFonts()
    lines = [HEADER, "#: family (lowercased) -> (unitsPerEm, ascent, descent, lineGap, superscript size,",
             "#: subscript size, superscript offset, subscript offset), as docx2svg.vertical.FaceMetrics.",
             "METRICS = {"]
    decorations, advances = {}, {}
    for family in FACES:
        face = fonts.face(family)
        if face is None or fonts.substitutions:
            print(f"{family} is not installed here: nothing recorded", file=sys.stderr)
            return 1
        m = face.metrics
        lines.append(f"    {family.lower()!r}: ({m.units_per_em}, {m.ascent}, {m.descent}, {m.line_gap}, "
                     f"{m.superscript_size}, {m.subscript_size}, {m.superscript_offset}, {m.subscript_offset}),")
        decorations[family.lower()] = face.decorations.integers()
        advances[family.lower()] = {code: face.advance(chr(code)) for r in RANGES for code in r
                                    if face.advance(chr(code)) is not None}
    lines.append("}")
    lines.append("")
    lines.append("#: family -> docx2svg.fonts.Decorations' integers, in its order.")
    lines.append("DECORATIONS = {")
    for family, values in decorations.items():
        lines.append(f"    {family!r}: {tuple(values)!r},")
    lines.append("}")
    lines.append("")
    lines.append("#: family -> {code point: advance, in font units}.")
    lines.append("ADVANCES = {")
    for family, table in advances.items():
        lines.append(f"    {family!r}: {{")
        items = [f"0x{code:04X}: {width}" for code, width in sorted(table.items())]
        for k in range(0, len(items), 6):
            lines.append("        " + ", ".join(items[k:k + 6]) + ",")
        lines.append("    },")
    lines.append("}")
    target = Path(sys.argv[sys.argv.index("--out") + 1]) if "--out" in sys.argv else TARGET
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
